from urllib.request import urlopen
from pprint import pprint     # makes complex data structures easier to read.

with urlopen ("https://www.example.com") as response:
#   pprint (dir(response))  # prints the built in object with all associate methods and atributes to it
# ['__abstractmethods__',
#  '__class__',
#  '__del__',
#  '__delattr__',
#  '__dict__',
#  '__dir__',
#  '__doc__',
#  '__enter__',
#  '__eq__',
#  '__exit__',
#  '__format__',
#  '__ge__',
#  '__getattribute__',
#  '__getstate__',
#  '__gt__',
#  '__hash__',
#  '__init__',
#  '__init_subclass__',
#  '__iter__',
#  '__le__',
#  '__lt__',
#  '__module__',
#  '__ne__',
#  '__new__',
#  '__next__',
#  '__reduce__',
#  '__reduce_ex__',
#  '__repr__',
#  '__setattr__',
#  '__sizeof__',
#  '__str__',
#  '__subclasshook__',
#  '_abc_impl',
#  '_checkClosed',
#  '_checkReadable',
#  '_checkSeekable',
#  '_checkWritable',
#  '_check_close',
#  '_close_conn',
#  '_get_chunk_left',
#  '_method',
#  '_peek_chunked',
#  '_read1_chunked',
#  '_read_and_discard_trailer',
#  '_read_chunked',
#  '_read_next_chunk_size',
#  '_read_status',
#  '_readinto_chunked',
#  '_safe_read',
#  '_safe_readinto',
#  'begin',
#  'chunk_left',
#  'chunked',
#  'close',
#  'closed',
#  'code',
#  'debuglevel',
#  'detach',
#  'fileno',
#  'flush',
#  'fp',
#  'getcode',
#  'getheader',
#  'getheaders',
#  'geturl',
#  'headers',    attribute -->
#  'info',
#  'isatty',
#  'isclosed',
#  'length',
#  'msg',
#  'peek',
#  'read',
#  'read1',
#  'readable',
#  'readinto',
#  'readinto1',
#  'readline',
#  'readlines',
#  'reason',
#  'seek',
#  'seekable',
#  'status',
#  'tell',
#  'truncate',
#  'url',
#  'version',
#  'will_close',
#  'writable',
#  'write',
#  'writelines']

    pass  #placeholder
    pprint(response.headers.items())
# [('Date', 'Fri, 11 Sep 2026 08:54:38 GMT'),
#  ('Content-Type', 'text/html'),
#  ('Transfer-Encoding', 'chunked'),
#  ('Connection', 'close'),
#  ('Server', 'cloudflare'),
#  ('last-modified', 'Thu, 10 Sep 2026 21:00:47 GMT'),
#  ('allow', 'GET, HEAD'),
#  ('Accept-Ranges', 'bytes'),
#  ('Age', '14134'),
#  ('cf-cache-status', 'HIT'),
#  ('CF-RAY', 'a39572ed6d3c196c-LHR')]